"""ReportLab → PDF bytes for complaint letters and collective dossiers.

Pure functions — they take the structured dicts produced by complaint_builder
and dossier_builder and emit PDF bytes. No file I/O, no HTTP.
"""

from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _styles():
    base = getSampleStyleSheet()
    base.add(
        ParagraphStyle(
            name="DocHeading",
            parent=base["Heading2"],
            spaceBefore=10,
            spaceAfter=6,
            textColor=colors.HexColor("#0b3954"),
        )
    )
    return base


def _header(complaint: dict[str, Any], styles) -> list:
    name = complaint.get("complainant_name") or "Anonymous PharmaWatch User"
    return [
        Paragraph(f"<b>From:</b> {name}", styles["Normal"]),
        Paragraph(f"<b>To:</b> {complaint['addressee']}", styles["Normal"]),
        Paragraph(f"<b>Date:</b> {complaint['letter_date']}", styles["Normal"]),
        Paragraph(f"<b>Subject:</b> {complaint['subject']}", styles["Normal"]),
        Spacer(1, 12),
    ]


def _section_paragraphs(section: dict[str, Any], styles) -> list:
    out: list = [Paragraph(section["heading"], styles["DocHeading"])]
    for para in section.get("paragraphs", []):
        out.append(Paragraph(para, styles["Normal"]))
    return out


def _section_table(section: dict[str, Any], columns: list[tuple[str, str]], styles) -> list:
    """Build a table from a section.rows list, given (header_label, key) pairs."""
    rows = section.get("rows", [])
    if not rows:
        return [
            Paragraph(section["heading"], styles["DocHeading"]),
            Paragraph("<i>None on record.</i>", styles["Normal"]),
        ]

    header = [c[0] for c in columns]
    body = [[str(r.get(k, "")) for _, k in columns] for r in rows]
    table = Table([header, *body], hAlign="LEFT", repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b3954")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f5f7")]),
            ]
        )
    )
    return [Paragraph(section["heading"], styles["DocHeading"]), table]


def render_complaint_pdf(complaint: dict[str, Any]) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm)
    styles = _styles()

    story: list = [
        Paragraph("PharmaWatch — Formal Complaint Letter", styles["Title"]),
        Spacer(1, 8),
        *_header(complaint, styles),
    ]
    for section in complaint["body_sections"]:
        story.extend(_section_paragraphs(section, styles))
        story.append(Spacer(1, 6))

    if complaint.get("citations"):
        story.append(Paragraph("Citations", styles["DocHeading"]))
        for c in complaint["citations"]:
            story.append(Paragraph(f"• {c['label']} — {c['source']}", styles["Normal"]))

    story.append(Spacer(1, 18))
    story.append(Paragraph(
        "Generated by PharmaWatch — built on DRAP's own public data.",
        styles["Italic"],
    ))

    doc.build(story)
    return buf.getvalue()


def render_dossier_pdf(dossier: dict[str, Any]) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm)
    styles = _styles()
    sections = dossier["sections"]

    story: list = [
        Paragraph("PharmaWatch — Collective Complaint Dossier", styles["Title"]),
        Spacer(1, 6),
        Paragraph(f"<b>To:</b> {dossier['addressee']}", styles["Normal"]),
        Paragraph(f"<b>Date:</b> {dossier['letter_date']}", styles["Normal"]),
        Paragraph(f"<b>Subject:</b> {dossier['subject']}", styles["Normal"]),
        Spacer(1, 10),
        *_section_paragraphs(sections["summary"], styles),
        Spacer(1, 6),
        *_section_table(
            sections["incidents"],
            [("Date", "date"), ("Medicine", "medicine"), ("DRAP MRP", "drap_mrp"),
             ("Charged", "charged"), ("% over MRP", "overcharge_pct"), ("DRAP Reg #", "drap_reg_number")],
            styles,
        ),
        Spacer(1, 6),
        *_section_table(
            sections["enforcement"],
            [("Date", "date"), ("Type", "violation_type"), ("Penalty", "penalty"),
             ("Amount (PKR)", "penalty_amount_pkr"), ("DRAP Notice", "drap_notice_ref"),
             ("Severity", "severity")],
            styles,
        ),
        Spacer(1, 8),
        *_section_paragraphs(sections["request"], styles),
        Spacer(1, 14),
        Paragraph(
            "Anonymous contributor count: " f"{dossier['stats']['total_reports']}. "
            "All evidence is publicly verifiable through the cited DRAP notice references.",
            styles["Italic"],
        ),
    ]

    doc.build(story)
    return buf.getvalue()
